apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-demo-php-config
  namespace: default
data:
  wordpress-custom.ini: |-
    upload_max_filesize = 50M
    post_max_size = 50M
  another-one.ini: |-
    some_other_php_stuff = true