apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-demo
  labels:
    app: mysql-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-demo
  template:
    metadata:
      labels:
        app: mysql-demo
    spec:
      containers:
        - image: mysql:5.6
          name: mysql-demo
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-demo
                  key: password
          ports:
            - containerPort: 3306
              name: mysql-demo
          volumeMounts:
            - name: mysql-persistent-storage-demo
              mountPath: /var/lib/mysql-demo
      volumes:
        - name: mysql-persistent-storage-demo
          persistentVolumeClaim:
            claimName: mysql-volumeclaim-demo
