apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress-demo
  name: wordpress-demo
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress-demo
