apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-demo
  labels:
    app: wordpress-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-demo
  template:
    metadata:
      labels:
        app: wordpress-demo
    spec:
      containers:
        - image: wordpress
          name: wordpress-demo
          env:
          - name: PHP_INI_SCAN_DIR
            value: :/usr/local/etc/php/conf.custom
          - name: WORDPRESS_DB_HOST
            value: mysql-demo:3306
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-demo
                key: password
          ports:
            - containerPort: 80
              name: wordpress-demo
          volumeMounts:
            - name: wordpress-persistent-storage-demo
              mountPath: /var/www/html
            - name: php-config
              mountPath: /usr/local/etc/php/conf.custom
      volumes:
        - name: wordpress-persistent-storage-demo
          persistentVolumeClaim:
            claimName: wordpress-volumeclaim-demo
        - name: php-config
          configMap:
            name: wordpress-demo-php-config
